[theme]
base = "light"
primaryColor = "#007F78"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17283C"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false
